"""__

Revision ID: 225b94dbeba6
Revises: c316b9874949
Create Date: 2025-03-02 14:24:03.647979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '225b94dbeba6'
down_revision: Union[str, None] = 'c316b9874949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userquestion', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userquestion', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
