"""__

Revision ID: 64555ecd41a8
Revises: 6a072d286489
Create Date: 2025-02-24 18:45:28.001033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '64555ecd41a8'
down_revision: Union[str, None] = '6a072d286489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userquestion', sa.Column('conversation_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'userquestion', 'conversation', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userquestion', type_='foreignkey')
    op.drop_column('userquestion', 'conversation_id')
    # ### end Alembic commands ###
