"""__

Revision ID: 6a072d286489
Revises: 45aba3354d61
Create Date: 2025-02-23 11:31:12.569723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a072d286489'
down_revision: Union[str, None] = '45aba3354d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aianswer', sa.Column('code_snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('aianswer', sa.Column('code_language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aianswer', 'code_language')
    op.drop_column('aianswer', 'code_snippet')
    # ### end Alembic commands ###
