import React from 'react'
import Link from 'next/link'

const page = () => {
  return (
    <div>
      <h1>Dev mentor</h1>
      <p>An Ai chatbot where you can ask questions and run the example code Generated by the AI</p>
      <Link href="/dashboard">Explore the app</Link>
    </div>
  )
}

export default page